-- Reset Database Script
-- This script completely resets the database for fresh setup

-- Drop all tables in correct order (to handle foreign key constraints)
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "support_tickets" CASCADE;
DROP TABLE IF EXISTS "email_logs" CASCADE;
DROP TABLE IF EXISTS "tickets" CASCADE;
DROP TABLE IF EXISTS "events" CASCADE;
DROP TABLE IF EXISTS "event_requests" CASCADE;
DROP TABLE IF EXISTS "categories" CASCADE;
DROP TABLE IF EXISTS "organizations" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "verification_tokens" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Drop old tables if they exist
DROP TABLE IF EXISTS "festivals" CASCADE;
DROP TABLE IF EXISTS "festival_requests" CASCADE;

-- Drop all enums
DROP TYPE IF EXISTS "Role" CASCADE;
DROP TYPE IF EXISTS "SupportPriority" CASCADE;
DROP TYPE IF EXISTS "SupportTicketStatus" CASCADE;
DROP TYPE IF EXISTS "EventStatus" CASCADE;
DROP TYPE IF EXISTS "RequestStatus" CASCADE;
DROP TYPE IF EXISTS "VenueType" CASCADE;
DROP TYPE IF EXISTS "TicketStatus" CASCADE;
DROP TYPE IF EXISTS "EmailStatus" CASCADE;

-- Drop all sequences (auto-generated by Prisma)
-- Note: These will be recreated by the migrations

-- Clear any remaining constraints or indexes
-- This ensures a completely clean slate